name: go-web-server

type: NodePort
ports:
  - port: 8080
    targetPort: 8080
    

container:
  image: shyamjesal/go-web-server
  imagePullPolicy: Always
  name: go-web-server
  ports:
    - containerPort: 8080
  env:
    - name: fqdn_suffix
      value: ".{{ .Release.Namespace }}.svc.cluster.local"
